--- 
baseurl: ""
description: "基于 jekyll 的 Github Pages 个人博客网站，技术的学习、总结、分享与提升\n"
exclude: 
  - Gemfile
  - Gemfile.lock
  - README.md
future: true
github_profile: "https://github.com/zhajj"
markdown: kramdown
paginate: 50
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
repository: zhajj/zjjblog
sass: 
  style: compressed
title: 萌新写手的博客
url: "https://zhajj.github.io/zjjblog/"
user: 萌新写手
user_email: 2534337852@qq.com
